[project]
name = "rag-core"
version = "0.1.0"
description = "Core RAG functionality for document processing, OCR, and vector search"
authors = [
    {name = "RAG Team", email = "team@example.com"}
]
dependencies = [
    "psycopg[binary]>=3.1.0",
    "redis>=5.0.0",
    "clickhouse-connect>=0.7.0",
    "ollama>=0.1.0",
    "langchain>=0.1.0",
    "langchain-community>=0.0.10",
    "pydantic>=2.5.0",
    "python-dotenv>=1.0.0",
    "toml>=0.10.2",
    "pillow>=10.0.0",
    "opencv-python>=4.8.0",
    "pytesseract>=0.3.10",
    "camelot-py[cv]>=0.11.0",
    "tabula-py>=2.8.0",
    "paddlepaddle>=2.5.0",
    "paddleocr>=2.7.0",
    "pypdf>=3.17.0",
    "python-docx>=1.1.0",
    "openpyxl>=3.1.0",
    "beautifulsoup4>=4.12.0",
    "lxml>=4.9.0",
    "email-validator>=2.0.0",
    "numpy>=1.24.0",
    "pandas>=2.0.0",
    "scikit-learn>=1.3.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["rag_core"]
