[app]
name = "RAG Platform"
version = "1.0.0"
debug = false

[database]
postgres_url = "postgresql://postgres:postgres@postgres:5432/rag_app"
redis_url = "redis://redis:6379/1"
clickhouse_url = "http://clickhouse:8123"

[ollama]
base_url = "http://ollama:11434"
llm_model = "llama3:8b"
embed_model = "bge-m3"

[rag]
chunk_size = 1000
chunk_overlap = 200
top_k = 20
top_rerank = 5
embedding_dim = 1024

[security]
secret_key = "CHANGE_ME_SECRET_KEY"
algorithm = "HS256"
access_token_expire_minutes = 30

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
