global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'rag-platform-prod'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # Node Exporter - system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # RAG Platform API
  - job_name: 'rag-api'
    static_configs:
      - targets: ['api:8081']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Nginx metrics (if nginx-prometheus-exporter is deployed)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s
    metrics_path: /metrics

  # PostgreSQL metrics (if postgres_exporter is deployed)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis metrics (if redis_exporter is deployed)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    metrics_path: /metrics

  # ClickHouse metrics
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
    scrape_interval: 30s
    metrics_path: /metrics
    params:
      query: ['SELECT 1']

  # Ollama metrics (if available)
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    scrape_interval: 30s
    metrics_path: /api/ps
    scrape_timeout: 10s

  # Streamlit health checks
  - job_name: 'streamlit-health'
    static_configs:
      - targets: ['streamlit:8502']
    scrape_interval: 30s
    metrics_path: /_stcore/health
    scrape_timeout: 5s

  # Custom application metrics from API
  - job_name: 'rag-platform-custom'
    static_configs:
      - targets: ['api:8081']
    scrape_interval: 30s
    metrics_path: /api/v1/metrics/prometheus
    scrape_timeout: 10s
    basic_auth:
      username: 'prometheus'
      password: 'your-prometheus-password'

  # Docker container metrics (if cAdvisor is deployed)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # Superset health monitoring
  - job_name: 'superset-health'
    static_configs:
      - targets: ['superset:8088']
    scrape_interval: 60s
    metrics_path: /health
    scrape_timeout: 10s

# Remote write configuration (for external monitoring systems)
# remote_write:
#   - url: "https://your-external-prometheus.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Remote read configuration (for external query)
# remote_read:
#   - url: "https://your-external-prometheus.com/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"
